CREATE SCHEMA injector;

CREATE TABLE injector.dcs_server
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255) NOT NULL,
    hostname VARCHAR(50)  NOT NULL,
    port     INTEGER      NOT NULL,
    password VARCHAR(100) NOT NULL,
    CONSTRAINT pk_dcs_server PRIMARY KEY (id)
);

ALTER TABLE injector.dcs_server
    ADD CONSTRAINT uc_dcs_server_name UNIQUE (name);